server:
  port: 9000
spring:
  profiles.active: dev

---

spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bookstore;MODE=MySQL
    initialize: false
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    initialize: true
  jpa:
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: create-drop
      show-sql: true