spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL

spring.jpa:
    hibernate.ddl-auto: create-drop

server:
  port: 9000

project:
  name: bookstore
  version: 0.1
  description: A simple Bookstore application with basic CRUD operations.
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}